In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
wines = pd.read_csv('data/winemag-data_first150k.csv')
wines_2 = pd.read_csv('data/winemag-data-130k-v2.csv')
wines

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude
...,...,...,...,...,...,...,...,...,...,...,...
150925,150925,Italy,Many people feel Fiano represents southern Ita...,NaN,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Feudi di San Gregorio
150926,150926,France,"Offers an intriguing nose with ginger, lime an...",Cuvée Prestige,91,27.0,Champagne,Champagne,NaN,Champagne Blend,H.Germain
150927,150927,Italy,This classic example comes from a cru vineyard...,Terre di Dora,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora
150928,150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset
150929,150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder

In [15]:
wines['title'] = (
    wines['winery'].fillna('') +
    " " +
    wines['variety'].fillna('') +
    " " +
    wines['designation'].fillna('')+
    " (" + 
    wines['region_1'].fillna('')+
    ") "
)

In [16]:
wines.loc[wines['country'] == "Italy"]

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,variety,winery,title
10,10,Italy,"Elegance, complexity and structure come togeth...",Ronco della Chiesa,95,80.0,Northeastern Italy,Collio,NaN,Friulano,Borgo del Tiglio,Borgo del Tiglio Friulano Ronco della Chiesa (...
32,32,Italy,"Underbrush, scorched earth, menthol and plum s...",Vigna Piaggia,90,NaN,Tuscany,Brunello di Montalcino,NaN,Sangiovese,Abbadia Ardenga,Abbadia Ardenga Sangiovese Vigna Piaggia (Brun...
35,35,Italy,"Forest floor, tilled soil, mature berry and a ...",Riserva,90,135.0,Tuscany,Brunello di Montalcino,NaN,Sangiovese,Carillon,Carillon Sangiovese Riserva (Brunello di Monta...
37,37,Italy,"Aromas of forest floor, violet, red berry and ...",NaN,90,29.0,Tuscany,Vino Nobile di Montepulciano,NaN,Sangiovese,Avignonesi,Avignonesi Sangiovese (Vino Nobile di Montepu...
38,38,Italy,"This has a charming nose that boasts rose, vio...",NaN,90,23.0,Tuscany,Chianti Classico,NaN,Sangiovese,Casina di Cornia,Casina di Cornia Sangiovese (Chianti Classico)
...,...,...,...,...,...,...,...,...,...,...,...,...
150920,150920,Italy,"Rich and mature aromas of smoke, earth and her...",Brut Riserva,91,19.0,Northeastern Italy,Trento,NaN,Champagne Blend,Letrari,Letrari Champagne Blend Brut Riserva (Trento)
150922,150922,Italy,Made by 30-ish Roberta Borghese high above Man...,Superiore,91,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,Tocai,Ronchi di Manzano,Ronchi di Manzano Tocai Superiore (Colli Orien...
150925,150925,Italy,Many people feel Fiano represents southern Ita...,NaN,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Feudi di San Gregorio,Feudi di San Gregorio White Blend (Fiano di A...
150927,150927,Italy,This classic example comes from a cru vineyard...,Terre di Dora,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora,Terredora White Blend Terre di Dora (Fiano di ...
150929,150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder,Alois Lageder Pinot Grigio (Alto Adige)

In [13]:
wines_2.loc[wines_2['country'] == "Italy"]

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
13,13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte
22,22,Italy,Delicate aromas recall white flower and citrus...,Ficiligno,87,19.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio di Pianetto 2007 Ficiligno White (Sicilia),White Blend,Baglio di Pianetto
24,24,Italy,"Aromas of prune, blackcurrant, toast and oak c...",Aynat,87,35.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Canicattì 2009 Aynat Nero d'Avola (Sicilia),Nero d'Avola,Canicattì
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129929,129929,Italy,"This luminous sparkler has a sweet, fruit-forw...",NaN,91,38.0,Veneto,Prosecco Superiore di Cartizze,NaN,NaN,NaN,Col Vetoraz Spumanti NV Prosecco Superiore di...,Prosecco,Col Vetoraz Spumanti
129943,129943,Italy,"A blend of Nero d'Avola and Syrah, this convey...",Adènzia,90,29.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio del Cristo di Campobello 2012 Adènzia R...,Red Blend,Baglio del Cristo di Campobello
129947,129947,Italy,"A blend of 65% Cabernet Sauvignon, 30% Merlot ...",Symposio,90,20.0,Sicily & Sardinia,Terre Siciliane,NaN,Kerin O’Keefe,@kerinokeefe,Feudo Principi di Butera 2012 Symposio Red (Te...,Red Blend,Feudo Principi di Butera
129961,129961,Italy,"Intense aromas of wild cherry, baking spice, t...",NaN,90,30.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,COS 2013 Frappato (Sicilia),Frappato,COS
129962,129962,Italy,"Blackberry, cassis, grilled herb and toasted a...",Sàgana Tenuta San Giacomo,90,40.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...,Nero d'Avola,Cusumano

In [17]:
wines_2 = wines_2.drop(['taster_name', 'taster_twitter_handle'], axis = 1)

In [19]:
wines_total = pd.concat([wines, wines_2])

In [22]:
wines_total = wines_total.reset_index()
wines_total['index'] = wines_total.index
wines_total = wines_total.drop('Unnamed: 0', axis = 1)
wines_total

,level_0,index,country,description,designation,points,price,province,region_1,region_2,variety,winery,title
0,0,0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz,Heitz Cabernet Sauvignon Martha's Vineyard (Na...
1,1,1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez,Bodega Carmen Rodríguez Tinta de Toro Carodoru...
2,2,2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley,Macauley Sauvignon Blanc Special Selected Late...
3,3,3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi,Ponzi Pinot Noir Reserve (Willamette Valley)
4,4,4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude,Domaine de la Bégude Provence red blend La Brû...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
280896,280896,280896,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef),Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...
280897,280897,280897,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Pinot Noir,Citation,Citation 2004 Pinot Noir (Oregon)
280898,280898,280898,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Gewürztraminer,Domaine Gresser,Domaine Gresser 2013 Kritt Gewurztraminer (Als...
280899,280899,280899,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Pinot Gris,Domaine Marcel Deiss,Domaine Marcel Deiss 2012 Pinot Gris (Alsace)
280900,280900,280900,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Gewürztraminer,Domaine Schoffit,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...

In [23]:
wines_total = wines_total.drop('level_0', axis =  1)
wines_total

,index,country,description,designation,points,price,province,region_1,region_2,variety,winery,title
0,0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz,Heitz Cabernet Sauvignon Martha's Vineyard (Na...
1,1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez,Bodega Carmen Rodríguez Tinta de Toro Carodoru...
2,2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley,Macauley Sauvignon Blanc Special Selected Late...
3,3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi,Ponzi Pinot Noir Reserve (Willamette Valley)
4,4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude,Domaine de la Bégude Provence red blend La Brû...
...,...,...,...,...,...,...,...,...,...,...,...,...
280896,280896,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef),Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...
280897,280897,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Pinot Noir,Citation,Citation 2004 Pinot Noir (Oregon)
280898,280898,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Gewürztraminer,Domaine Gresser,Domaine Gresser 2013 Kritt Gewurztraminer (Als...
280899,280899,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Pinot Gris,Domaine Marcel Deiss,Domaine Marcel Deiss 2012 Pinot Gris (Alsace)
280900,280900,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Gewürztraminer,Domaine Schoffit,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...

In [24]:
wines_total.to_csv('data/wines_db.csv')

In [34]:
wines_total.loc[wines_total['description'].str.len() < 50]

,index,country,description,designation,points,price,province,region_1,region_2,variety,winery,title
12922,12922,US,A very simple Chardonnay with sour apple flavor.,NaN,83,14.0,California,Mendocino County,Mendocino/Lake Counties,Chardonnay,Green Truck,Green Truck Chardonnay (Mendocino County)
17024,17024,US,Watery and heavy in super-oaked flavors.,NaN,82,11.0,California,California,California Other,Chardonnay,Avenue,Avenue Chardonnay (California)
17030,17030,US,"Odd and medicinal, with a harsh, burnt taste.",NaN,81,18.0,California,Lake County,Mendocino/Lake Counties,Primitivo,Rosa d'Oro,Rosa d'Oro Primitivo (Lake County)
18827,18827,US,Judi Sorensen Flom,Signature Collection,85,29.0,Oregon,Oregon,Oregon Other,Pinot Noir,King Estate,King Estate Pinot Noir Signature Collection (O...
19353,19353,US,"Barely acceptable. Dry, harsh and vegetal.",Discovery,80,11.0,California,Alexander Valley,Sonoma,Cabernet Sauvignon,Q,Q Cabernet Sauvignon Discovery (Alexander Vall...
...,...,...,...,...,...,...,...,...,...,...,...,...
246171,246171,US,A very simple Chardonnay with sour apple flavor.,NaN,83,14.0,California,Mendocino County,NaN,Chardonnay,Green Truck,Green Truck 2011 Chardonnay (Mendocino County)
260155,260155,US,"This is acidic and sweet, with a medicinal taste.",Hayley Vineyard,80,36.0,California,Anderson Valley,NaN,Pinot Noir,Bryter,Bryter 2009 Hayley Vineyard Pinot Noir (Anders...
262965,262965,US,"Dusty, chalky and thin, with little fruit.",NaN,82,26.0,Oregon,Umpqua Valley,Southern Oregon,Tempranillo,Reustle,Reustle 2008 Tempranillo (Umpqua Valley)
267948,267948,US,"Smells raisiny, feels hot, tastes overripe.",Imagine Reserve,81,62.0,California,Santa Barbara County,Central Coast,Pinot Noir,Hunt Cellars,Hunt Cellars 2009 Imagine Reserve Pinot Noir (...
269534,269534,South Africa,Imported by Maisons Marques & Domaines USA.,NaN,86,12.0,Coastal Region,NaN,NaN,Merlot,Fleur Du Cap,Fleur Du Cap 2004 Merlot (Coastal Region)

In [33]:
wines_total['description'].str.len().mean()

np.float64(241.40442006258434)

In [36]:
(280901 + 100-1)/100

2810.0

In [38]:
len(wines_total.drop_duplicates('title'))

187009

In [9]:
import os
import json
from dotenv import load_dotenv
load_dotenv()

from openai import OpenAI
from google import genai
from backend.embeddings import get_recommended_wines
from backend.prompting import (
    SYSTEM_PROMPT,
    build_recommendation_prompt,
    build_refinement_prompt,
    parse_recommendation_response,
    start_conversation,
)

CLIENT = genai.Client(api_key=os.getenv("GOOGLE_API_KEY"))
USE_MODEL  = "gemini-2.5-flash"

# ---------------------------------------------------------------------------
# Fake data — representative of what embeddings.py + SQLite would provide
# ---------------------------------------------------------------------------

MOCK_PROFILE = {
    "sweetness": "dry",
    "body": "full",
    "tannins": "high",
    "acidity": "medium",
    "favorite_flavors": json.dumps(["dark cherry", "oak", "tobacco", "leather"]),
    "price_min": 20.0,
    "price_max": 70.0,
    "preferred_wine_types": json.dumps(["red"]),
    "preferred_regions": json.dumps(["Bordeaux", "Napa Valley"]),
    "additional_notes": "Prefers Old World structure when possible.",
}

MOCK_RESULTS = get_recommended_wines("I want something bold to pair with a ribeye steak tonight")
for i, wine in enumerate(MOCK_RESULTS):
    print(f"  #{i+1} {wine['title'] or wine['winery']}"
          f" ({wine['variety']})"
          f" ${wine['price']:.0f} | {wine['points']}pts"
          f" | similarity: {wine['similarity']}")
    print(f"       {wine['description'][:100]}...")
    print()

def call_google(messages: str, system = SYSTEM_PROMPT) -> str:
    """Fire a Google API call and return the raw text response."""
    response = CLIENT.models.generate_content(
        model=USE_MODEL,
        contents=messages,
        config = {"system_instruction" : SYSTEM_PROMPT}
    )
    return response.text


def test_initial_recommendation():
    print("=" * 60)
    print("Test 1: Initial recommendation")
    print("=" * 60)

    messages = build_recommendation_prompt(
        query="I want something bold to pair with a ribeye steak tonight",
        candidates=MOCK_CANDIDATES,
        profile=MOCK_PROFILE,
        n_recommendations=3,
    )

    print(f"\nSending {len(MOCK_CANDIDATES)} candidates to Google...")
    raw = call_google(messages)

    print("\nRaw Gemini response:")
    print(raw)

    parsed = parse_recommendation_response(raw)
    assert parsed is not None, "Response failed to parse as JSON"
    assert parsed.recommendations, "Missing recommendations"
    assert parsed.sommelier_note, "Missing sommelier_note"
    assert len(parsed.recommendations) == 3, \
    f"Expected 3 recommendations, got {len(parsed.recommendations)}"

    print(f"\nSommelier note: {parsed.sommelier_note[:100]}...")
    for rec in parsed.recommendations:
        wine = MOCK_CANDIDATES[rec.candidate_index - 1]
        print(f"\n  #{rec.candidate_index} {wine['title']}")
        print(f"  Rationale: {rec.rationale[:120]}...")
        if rec.food_pairing:
            print(f"  Pairing: {rec.food_pairing[:100]}...")
        if rec.serving_suggestion:
            print(f"  Serving: {rec.serving_suggestion}")
    return messages, raw


def test_refinement(initial_messages: list[dict], initial_response: str):
    print("=" * 60)
    print("Test 2: Refinement request")
    print("=" * 60)

    history = start_conversation(initial_messages, initial_response)

    # Simulate user wanting something different
    feedback = "These feel too tannic and heavy. " \
               "Can you suggest something a bit more elegant and approachable, " \
               "maybe with more finesse than power?"

    # In real usage, new_candidates would come from a fresh ChromaDB query
    # using the feedback. For this test we reuse the same candidates.
    messages = build_refinement_prompt(
        feedback=feedback,
        new_candidates=MOCK_CANDIDATES,
        conversation_history=history,
        profile=MOCK_PROFILE,
        n_recommendations=3,
    )

    print(f"\nConversation history length: {len(messages)} messages")
    print(f"Feedback: \"{feedback}\"")
    print("\nSending refinement to Gemini...")

    raw = call_google(messages)

    print("\nRaw Gemini response:")
    print(raw)

    parsed = parse_recommendation_response(raw)
    assert parsed is not None, "Refinement response failed to parse as JSON"
    assert parsed.recommendations, "Missing recommendations"
    assert len(parsed.recommendations) == 3

    print("\nRefined recommendations:")
    for rec in parsed.recommendations:
        wine = MOCK_CANDIDATES[rec.candidate_index - 1]
        print(f"\n  #{rec.candidate_index} {wine['title']}")
        print(f"  Rationale: {rec.rationale[:120]}...")

    print("\n✓ Test 2 passed\n")


print("Testing prompt pipeline...\n")

initial_messages, initial_response = test_initial_recommendation()
test_refinement(initial_messages, initial_response)

print("=" * 60)
print("  All prompt tests passed ✓")
print("=" * 60)

  #1 Prospect 772 Red Blend Black Tie Charlie (California) (Red Blend) $27 | 89pts | similarity: 0.5751
       This wine is powerful enough to serve with wild boar carpaccio, if there is such a thing, or with bl...

  #2 Raymond Cabernet Sauvignon  (Rutherford) (Cabernet Sauvignon) $50 | 92pts | similarity: 0.5309
       While this gorgeous Cab shows a ripe approachability that makes it instantly drinkable, it also has ...

  #3 Angus The Bull Cabernet Sauvignon  (South Eastern Australia) (Cabernet Sauvignon) $18 | 87pts | similarity: 0.5505
       According to the winemaker, this is specifically tailored to go with red meat and the truth is, it w...

  #4 Bodega Norton Bordeaux-style Red Blend Perdriel Single Vineyard (Mendoza) (Bordeaux-style Red Blend) $64 | 94pts | similarity: 0.4803
       As good as it gets from Argentina. Winemaker Jorge Riccitelli has artfully crafted a bruising but lo...

  #5 MandraRossa Red Blend Bonera (Sicilia) (Red Blend) $20 | 87pts | similarity: 0.4928
       An easydrinking blend of Nero d'Avola and Cabernet Sauvignon and Cabernet Franc, this would pair wel...

  #6 Mil Piedras Cabernet Sauvignon  (Mendoza) (Cabernet Sauvignon) $13 | 86pts | similarity: 0.4804
       Blueberry and cassis aromas are jammy and suggest graham crackers. This feels tight and narrow, with...

  #7 Whalebone 2013 Bob Wine Red (Paso Robles) (Red Blend) $34 | 88pts | similarity: 0.4821
       This blend of 63% Cabernet Sauvignon, 30% Merlot and 7% Petit Sirah is fun yet serious, with roast b...

  #8 Bodegas Peñafiel Red Blend Miros de Ribera Crianza (Ribera del Duero) (Red Blend) $28 | 87pts | similarity: 0.467
       Good wine from a very hot year. Early aromas of Band-Aid and barnyard fade with airing, and then for...

  #9 Billsboro Cabernet Sauvignon  (Finger Lakes) (Cabernet Sauvignon) $20 | 84pts | similarity: 0.4773
       Black fruit and cherry leads on this balanced red. Flavors of black pepper, black currant and plum o...

  #10 Original House Wine 2015 Steak House Cabernet Sauvignon (America) (Cabernet Sauvignon) $12 | 86pts | similarity: 0.5201
       The aromas are fruit forward, with notes of berry and black currant. The flavors are ripe, with the ...

Testing prompt pipeline...

============================================================
Test 1: Initial recommendation
============================================================

Sending 5 candidates to Google...

ClientError: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 9.864098699s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '9s'}]}}

In [ ]:
print("Available Gemini models:")
for m in genai.list_models():
    if 'generateContent' in m.supported_generation_methods:
        print(f"  ✓ {m.name}")